### ISSUE TITLE
No popup is opened for sublayer of group or mapimage layers

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-omnisearch-autoinfo#3]
In this app you can see different combinations of layers. The bundle currently only works for feature layers.

https://demos.conterra.de/sandbox/resources/apps/test-omnisearch-auto/index.html

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-omnisearch-autoinfo/releases/tag/2.0.1
